# Introduction {#intro}

## Preamble

- Coggle Diagrams
- Lean on visualizations as much as possible first to introduce summary measures
- We will focus on the triad: computational, data, and inferential thinking.
    + Literate programming / literate data science
    + "Programs must be written for people to read, and only incidentally for machines to execute." - Hal Abelson
- Discuss the role of data analysis in the sciences
- Explain why programming and data science help scientific knowledge grow

## Data/science pipeline



## Reproducibility

* "The most important tool is the _mindset_,
when starting, that the end product
will be reproducible." – Keith Baggerly

* "We are talking about _computational_ reproducibility." - Yihui Xie

## Who is this book for? (Target)


Students taking a traditional intro stats class in a small college environment using RStudio preferably RStudio Server. 

We assume no prerequisites: no calculus and no prior programming experience.  

*To think about further*
