# Visualizing Data {#viz}

<!--
Cover grammar of graphics?  Yes, we definitely should.

Theoretical discussion of the grammar of graphics
  - Menard example
  
Five named graphs
  - Breakdown of their components with geoms
  - In particular histogram as a visual representation of distribution. i.e. it is an empirical distribution as an estimate of population distribution.
-->

In Chapter \@ref(tidy), we discussed the importance of datasets being **tidy**.  You will see in examples here why having a tidy dataset helps us immensely with plotting our data.  We will focus on using Hadley's `ggplot2` package in doing so, which was developed to work specifically on datasets that are **tidy**.  It provides an easy way to customize your plots and is based on data visualization theory given in _The Grammar of Graphics_ [@wilkinson2005].

## Five Named Graphs. FNG

* Focussing on `dep_delay` here and how it relates with other variables
* May need to introduce some data manipulation here with `dplyr`
* Restrict types of plots:
    + histogram: as long as we avoid density plots
    + boxplot: have to set x=1 aes. categorical variables when univariate
        - Hadley suggests that a univariate boxplot shouldn't be used and prefers a histogram <https://groups.google.com/forum/#!topic/ggplot2/N4qRSmqMZxI>
        - Boxplots do make sense when comparing distributions across levels of another variable though
    + barplot: issue with categorical variables 
        - May want to also discuss dot plots for many levels of categorical variable
    + scatterplot: jitter/alpha/color
    + linegraph: useful for time series / not useful if no ordering to x-values
    + faceting: show why better than stacked bargraphs in via patterns across levels
    + mosaicplot [I actually prefer side-by-side bar graphs/facetted bargraphs to stacked/mosaic so this might be moot?]

### Review questions

- Have a variety of bad plots with data for the readers and have readers create better plots with `ggplot2`
