<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A MODERN DIVE into the Language of Science</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Getting away from the traditional introductory statistical curriculum more focused on reproducible research and modern data analysis techniques and tools">
  <meta name="generator" content="bookdown 0.1.2 and GitBook 2.6.7">

  <meta property="og:title" content="A MODERN DIVE into the Language of Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Getting away from the traditional introductory statistical curriculum more focused on reproducible research and modern data analysis techniques and tools" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A MODERN DIVE into the Language of Science" />
  
  <meta name="twitter:description" content="Getting away from the traditional introductory statistical curriculum more focused on reproducible research and modern data analysis techniques and tools" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">

<meta name="date" content="2016-07-29">


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="tidy.html">
<link rel="next" href="manip.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="prereqs.html"><a href="prereqs.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="1.1" data-path="prereqs.html"><a href="prereqs.html#colophon"><i class="fa fa-check"></i><b>1.1</b> Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#preamble"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.2</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#reproducibility"><i class="fa fa-check"></i><b>2.3</b> Reproducibility</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#who-is-this-book-for-target"><i class="fa fa-check"></i><b>2.4</b> Who is this book for? (Target)</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#algorithmic-thinking"><i class="fa fa-check"></i><b>2.5</b> Algorithmic Thinking</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy data</a><ul>
<li class="chapter" data-level="3.1" data-path="tidy.html"><a href="tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="tidy.html"><a href="tidy.html#the-nycflights13-datasets"><i class="fa fa-check"></i><b>3.2</b> The <code>nycflights13</code> datasets</a></li>
<li class="chapter" data-level="3.3" data-path="tidy.html"><a href="tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a></li>
<li class="chapter" data-level="3.4" data-path="tidy.html"><a href="tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="tidy.html"><a href="tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Visualizing Data</a><ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#five-named-graphs---the-fng"><i class="fa fa-check"></i><b>4.1</b> Five Named Graphs - The FNG</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#histograms"><i class="fa fa-check"></i><b>4.2</b> Histograms</a><ul>
<li class="chapter" data-level="4.2.1" data-path="viz.html"><a href="viz.html#continuous-data-summaries"><i class="fa fa-check"></i><b>4.2.1</b> Continuous data summaries</a></li>
<li class="chapter" data-level="4.2.2" data-path="viz.html"><a href="viz.html#summary"><i class="fa fa-check"></i><b>4.2.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#boxplots"><i class="fa fa-check"></i><b>4.3</b> Boxplots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="viz.html"><a href="viz.html#facetting"><i class="fa fa-check"></i><b>4.3.1</b> Facetting</a></li>
<li class="chapter" data-level="4.3.2" data-path="viz.html"><a href="viz.html#summary-1"><i class="fa fa-check"></i><b>4.3.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#barplots"><i class="fa fa-check"></i><b>4.4</b> Barplots</a><ul>
<li class="chapter" data-level="4.4.1" data-path="viz.html"><a href="viz.html#categorical-data-summaries"><i class="fa fa-check"></i><b>4.4.1</b> Categorical data summaries</a></li>
<li class="chapter" data-level="4.4.2" data-path="viz.html"><a href="viz.html#summary-2"><i class="fa fa-check"></i><b>4.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#scatter-plots"><i class="fa fa-check"></i><b>4.5</b> Scatter-plots</a><ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#summary-3"><i class="fa fa-check"></i><b>4.5.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#line-graphs"><i class="fa fa-check"></i><b>4.6</b> Line-graphs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="viz.html"><a href="viz.html#summary-4"><i class="fa fa-check"></i><b>4.6.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#brief-review-of-the-grammar-of-graphics"><i class="fa fa-check"></i><b>4.7</b> Brief Review of The Grammar of Graphics</a><ul>
<li class="chapter" data-level="4.7.1" data-path="viz.html"><a href="viz.html#review-questions"><i class="fa fa-check"></i><b>4.7.1</b> Review questions</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="viz.html"><a href="viz.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.8</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manip.html"><a href="manip.html"><i class="fa fa-check"></i><b>5</b> Manipulating Data</a></li>
<li class="chapter" data-level="6" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>6</b> Inference</a></li>
<li class="chapter" data-level="7" data-path="appendix1.html"><a href="appendix1.html"><i class="fa fa-check"></i><b>7</b> Appendix A: R and RStudio Basics</a></li>
<li class="chapter" data-level="8" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>8</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A <em>MODERN DIVE</em> into the Language of Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="viz" class="section level1">
<h1><span class="header-section-number">4</span> Visualizing Data</h1>
<!--
Cover grammar of graphics?  Yes, we definitely should.

Theoretical discussion of the grammar of graphics
  - Menard example
  
Five named graphs
  - Breakdown of their components with geoms
  - In particular histogram as a visual representation of distribution. i.e. it is an empirical distribution as an estimate of population distribution.
-->
<p>In Chapter <a href="tidy.html#tidy">3</a>, we discussed the importance of datasets being <strong>tidy</strong>. You will see in examples here why having a tidy dataset helps us immensely with plotting our data. We will focus on using Hadley’s <code>ggplot2</code> package in doing so, which was developed to work specifically on datasets that are <strong>tidy</strong>. It provides an easy way to customize your plots and is based on data visualization theory given in <em>The Grammar of Graphics</em> <span class="citation">(Wilkinson <a href="#ref-wilkinson2005">2005</a>)</span>.</p>
<p>Graphics provide a nice way for us to get a sense for how quantitative variables compare in terms of their center and their spread. It also helps us to identify patterns and outliers in our data. We will see that a common extension of these ideas is to compare the distribution (i.e., what the spread of a variable looks like) as we go across the levels of a different categorical variable.</p>
<div id="five-named-graphs---the-fng" class="section level2">
<h2><span class="header-section-number">4.1</span> Five Named Graphs - The FNG</h2>
<!--
* Focussing on `dep_delay` here and how it relates with other variables
* May need to introduce some data manipulation here with `dplyr`
* Restrict types of plots:
    + histogram: as long as we avoid density plots
    + boxplot: have to set x=1 aes. categorical variables when univariate
        - Hadley suggests that a univariate boxplot shouldn't be used and prefers a histogram <https://groups.google.com/forum/#!topic/ggplot2/N4qRSmqMZxI>
        - Boxplots do make sense when comparing distributions across levels of another variable though
    + barplot: issue with categorical variables 
        - May want to also discuss dot plots for many levels of categorical variable
    + scatterplot: jitter/alpha/color
    + linegraph: useful for time series / not useful if no ordering to x-values
    + faceting: show why better than stacked bargraphs in via patterns across levels
    + mosaicplot [I actually prefer side-by-side bar graphs/facetted bargraphs to stacked/mosaic so this might be moot?]
-->
<p>For our purposes here, we will be working with five different types of graphs. (Note that we will use a lot of different words here in regards to plotting - “graphs”, “plots”, and “charts” are all ways to discuss a resulting graphic. You can think of them as all being synonyms.) These five plots are:</p>
<ul>
<li>histograms</li>
<li>boxplots</li>
<li>barplots</li>
<li>scatter-plots</li>
<li>line-graphs</li>
</ul>
<p>With this toolbox of plots, you can visualize just about any type of variable thrown at you. We will discuss some other variations of these but with the FNG in your repertoire you can do big things! Something we will also stress here is that certain plots only work for categorical/logical variables and others only for quantitative variables. You’ll want to quiz yourself often on which plot makes sense with a given problem set-up.</p>
<p>We now introduce another dataframe in the <code>nycflights13</code> package introduced in Chapter <a href="tidy.html#tidy">3</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(nycflights13)
<span class="kw">data</span>(weather)</code></pre></div>
</div>
<div id="histograms" class="section level2">
<h2><span class="header-section-number">4.2</span> Histograms</h2>
<p>Our focus now turns to the <code>temp</code> variable in this <code>weather</code> dataset. We would like to visualize what the 26130 temperatures look like. Looking over the <code>weather</code> dataset<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> and running <code>?weather</code>, we can see that the <code>temp</code> variable corresponds to hourly temperature (in Fahrenheit) recordings at weather stations near airports in New York City. We could just produce points where each of the different values appears on something similar to a number line:</p>
<div class="figure"><span id="fig:unnamed-chunk-12"></span>
<img src="ismay_kim_files/figure-html/unnamed-chunk-12-1.png" alt="Strip Plot of Hourly Temperature Recordings from NYC in 2013" width="672" />
<p class="caption">
Figure 4.1: Strip Plot of Hourly Temperature Recordings from NYC in 2013
</p>
</div>
<p>This gives us a general idea of how the values of <code>temp</code> differ. We see that temperatures vary from around 11 up to 100 degrees Fahrenheit. The area between 40 and 60 degrees appears to have more points plotted than outside that range.</p>
<p>What is commonly produced instead of this strip plot is a plot known as a <strong>histogram</strong>. The <strong>histogram</strong> show how many elements of the variable fall in specified <strong>bins</strong>. These <strong>bins</strong> may correspond to between 0-10°F, 10-20°F, etc.</p>
<p>To produce a histogram, we introduce the Hadley’s <code>ggplot2</code> package <span class="citation">(Wickham and Chang <a href="#ref-R-ggplot2">2016</a>)</span>. We will use the <code>ggplot</code> function which expects at a bare minimal as arguments</p>
<ul>
<li>the dataframe where the variables exist and</li>
<li>the names of the variables to be plotted.</li>
</ul>
<p>The names of the variables will be entered into the <code>aes</code> function as arguments where <code>aes</code> stands for “aesthetics”.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp))</code></pre></div>
<p><img src="ismay_kim_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The plot given above is not a histogram, but the output does show us a bit of what is going on with <code>ggplot(data = weather, mapping = aes(x = temp))</code>. It is producing a backdrop onto which we will “paint” elements.</p>
<p>We next proceed by adding a layer—hence, the use of the <code>+</code> symbol—to the plot to produce a histogram. (Note also here that we don’t have to specify the <code>data =</code> and <code>mapping =</code> text in our function calls. This is covered in more detail in Appendix A - Chapter <a href="appendix1.html#appendix1">7</a>.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>()</code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_bin).</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-14"></span>
<img src="ismay_kim_files/figure-html/unnamed-chunk-14-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013" width="672" />
<p class="caption">
Figure 4.2: Histogram of Hourly Temperature Recordings from NYC in 2013
</p>
</div>
<p>We have the power to specify how many bins we would like to put the data into as an argument in the <code>geom_histogram</code> function. By default, this is chosen to be 30 somewhat arbitrarily and we have received a warning above our plot that this was done. We also notice here that another warning about 1 missing value is given. This value is omitted from the plot. This warning is ignored for future customizations of the plot. (<strong>Discuss missing values here?</strong>)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">60</span>)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-15"></span>
<img src="ismay_kim_files/figure-html/unnamed-chunk-15-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013 - 60 Bins" width="672" />
<p class="caption">
Figure 4.3: Histogram of Hourly Temperature Recordings from NYC in 2013 - 60 Bins
</p>
</div>
<p>We can tweak the plot a little more by specifying the width of the bins (instead of how many bins to divide the variable into) by using the <code>binwidth</code> argument in the <code>geom_histogram</code> function. We can also add some color to the plot by invoking the <code>fill</code> and <code>color</code> arguments. A listing of all of the built-in colors to R by name and color is available <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf">here</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;forestgreen&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-16"></span>
<img src="ismay_kim_files/figure-html/unnamed-chunk-16-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013 - Binwidth = 10" width="672" />
<p class="caption">
Figure 4.4: Histogram of Hourly Temperature Recordings from NYC in 2013 - Binwidth = 10
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.1</strong> What does changing the number of bins from 30 to 60 tell us about the distribution of temperatures?
</p>
<p>
<strong>4.2</strong> Would you classify the distribution of temperatures as symmetric or skewed?
</p>
<p>
<strong>4.3</strong> What would you guess is the “center” value in this distribution? Why did you make that choice?
</p>
<p>
<strong>4.4</strong> Is this data spread out greatly from the center or is it close? Why?
</p>
</div>
<div id="continuous-data-summaries" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Continuous data summaries</h3>
<p>The <code>temp</code> variable is a <strong>continuous</strong> quantitative variable (frequently just called a <strong>continuous variable</strong>). “A variable is <strong>continuous</strong> if you can arrange its values in order and an infinite number of unique values can exist between any two values of the variable”<span class="citation">(Wickham and Grolemund <a href="#ref-r4ds2016">2016</a>)</span>. Some common examples of continuous variables are time and height. Between any two times there are an infinitely many number of time units that fall between them.</p>
<p>It is often easier to think about quantitative variables that are not continuous to help us better understand continuity. The best example is counts. If we are looking to count the number of flights that depart on a given day from New York City, this variable would not be continuous. It falls on a <strong>discrete</strong> scale.</p>
<p>We can examine some summary information about this <code>temp</code> variable. To do so, we introduce the <code>summary</code> function. (We will see in Chapter <a href="manip.html#manip">5</a> how to use the <code>summarize</code> function in the <code>dplyr</code> package to produce similar results.)</p>
<p>The syntax here is a little different than what we have seen before. (A further discussion about R syntax is available in Appendix A - Chapter <a href="appendix1.html#appendix1">7</a>). Here <code>summary</code> is the function and it is expecting an object to be summarized as its argument. The object here is the <code>temp</code> variable in the <code>weather</code> dataframe. To focus on just this one variable <code>temp</code> in <code>weather</code>, we separate them by the dollar sign symbol <code>$</code>. Order matters here: the dataframe comes before the <code>$</code> and the variable/column name comes after.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(weather$temp)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   10.94   39.92   55.04   55.20   69.98  100.00       1</code></pre>
<p>This tells us what is known as the <strong>five-number summary</strong> for our variable as well as the <strong>mean</strong> value of the variable. More information on both of these concepts is given in Appendix A - Chapter <a href="appendix1.html#appendix1">7</a>.</p>
<p>This <code>summary</code> gives us some numerical summaries of our temperature variable. The minimum recorded temperature is 10.94 degrees Fahrenheit and the maximum is 100.04 degrees Fahrenheit. We have one missing value denoted as an <code>NA</code> in the observations of this variable. The median Fahrenheit temperature of 55.04 and mean of 55.2035149 are quite close. This is a property of symmetric distributions.</p>
<p>The last two entries given by <code>summary</code> correspond to the 25<sup>th</sup> percentile and the 75<sup>th</sup> percentile. If we sorted all of the temperatures in increasing order, we would see that 25% of them would fall below 39.92 and that 75% of them would fall below 69.98. This implies that the middle 50% of data values lie between 39.92 and 69.98 degrees Fahrenheit.</p>
<p><strong>Introduce standard deviation here?</strong></p>
</div>
<div id="summary" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Summary</h3>
<p>Histograms provide a useful way of looking at how ONE continuous variable varies. They allow us to answer questions such as</p>
<ul>
<li>Are there values far away from the center? These are commonly called <strong>outliers</strong> and can frequently be easily identified on a histogram.</li>
<li>Are most values close to the center? If so, the spread of the variable is small. If not, the spread is large.</li>
<li>How spread out are the values? One measure of this spread is <strong>standard deviation</strong> discussed above.</li>
</ul>
<p>The histogram show how many entries fall in different groupings of this variable. Another common property of distributions is symmetry and as we saw it is quite easily identified by looking over the histogram produced from the variable’s values.</p>
</div>
</div>
<div id="boxplots" class="section level2">
<h2><span class="header-section-number">4.3</span> Boxplots</h2>
<p>Histograms can also be produced to compare the distribution of a variable over another variable. Suppose we were interested in looking at how the temperature recordings we saw in the last section varied by month. This is what is meant by “the distribution of a variable over another variable”.</p>
<div id="facetting" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Facetting</h3>
<p>In order to look at histograms of <code>temp</code> for each month, we introduce a new concept called <strong>facetting</strong>. Faceting is used when we’d like to create small multiples of the same plot over a different categorical variable. By default, all of the small multiples will have the same vertical axis. An example will help here. We will discuss the concept of faceting in further detail in Section @ref{barplots}.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;firebrick&quot;</span>) +
<span class="st">  </span><span class="kw">facet_wrap</span>(~month)</code></pre></div>
<p><img src="ismay_kim_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>As we might expect, the temperature tends to increase as summer approaches and then decrease as winter approaches.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.5</strong> What other things do you notice about the faceted plot above? How does a faceted plot help us see how relationships between two variables?
</p>
<p>
<strong>4.6</strong> What do the numbers 1-12 correspond to in the plot above? What about 25, 50, 75, 100?
</p>
<p>
<strong>4.7</strong> What could be done to make the faceted plot above more readable? (Focus on tweaking the histograms and not on making a different type of plot here.)
</p>
<p>
<strong>4.8</strong> For which types of datasets would these types of faceted plots not work well in comparing relationships between variables? Draw or give an example.
</p>
</div>
<p>Histograms can provide a way to compare distributions across groups as we see above when we looked at temperature over months. Frequently, a plot called a <strong>boxplot</strong> (also called a <strong>side-by-side boxplot</strong>) is done instead. The <strong>boxplot</strong> uses the information provided in the <strong>five-number summary</strong> referred to in the previous section when we used the <code>summary</code> function. It gives a way to compare this summary information across the different levels of a group. Let’s create a boxplot to compare the monthly temperatures as we did above with the faceted histograms.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> temp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<pre><code>## Warning: Continuous x aesthetic -- did you forget aes(group=...)?</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="ismay_kim_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Note the first warning that is given here. (The second one corresponds to missing values in the dataframe and it is turned off on subsequent plots.) This plot does not look like what we were expecting. We were expecting to see the distribution of temperatures for each month (so 12 different boxplots). This gives us the overall boxplot without any other groupings. We can get around this by introducing a new function for our <code>x</code> variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(month), <span class="dt">y =</span> temp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<p><img src="ismay_kim_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>We have introduced a new function called <code>factor()</code> here. One of the things this function does is to convert a numeric value like <code>month</code> (1, 2, …, 12) into a categorical variable. The “box” part of this plot represents the 25<sup>th</sup> percentile, the median (50<sup>th</sup> percentile), and the 75<sup>th</sup> percentile. The dots correspond to <strong>outliers</strong>. (The specific formulation for these outliers is discussed in Appendix A - Chapter <a href="appendix1.html#appendix1">7</a>.) The lines show how the data varies that is not in the center 50% defined by the first and third quantiles. Longer lines correspond to more variability and shorter lines correspond to less variability.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.9</strong> What does the dot at the bottom of the plot for May correspond to? Explain what might have occurred in May to produce this point.
</p>
<p>
<strong>4.10</strong> Which months have the highest variability in temperature? What reasons do you think this is?
</p>
<p>
<strong>4.11</strong> We looked at the distribution of a continuous variable over a categorical variable here with this boxplot. Why can’t we look at the distribution of one continuous variable over the distribution of another continuous variable? Say temperature across pressure, for example?
</p>
<p>
<strong>4.12</strong> Boxplots provide a simple way to identify outliers. Why may outliers be easier to identify when looking at a boxplot instead of a faceted histogram?
</p>
</div>
</div>
<div id="summary-1" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Summary</h3>
<p>Boxplots provide a way to compare and contrast the distribution of ONE quantitative variable across multiple levels of ONE categorical variable. One can easily look to see where the median falls across the different groups by looking at the center line in the box. You can also see how spread out the variable is across the different groups by looking at the width of the box and also how far out the lines stretch from the box. Lastly, outliers are even more easily identified when looking at a boxplot than when looking at a histogram.</p>
</div>
</div>
<div id="barplots" class="section level2">
<h2><span class="header-section-number">4.4</span> Barplots</h2>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.</strong>
</p>
</div>
<div id="categorical-data-summaries" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Categorical data summaries</h3>
</div>
<div id="summary-2" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Summary</h3>
</div>
</div>
<div id="scatter-plots" class="section level2">
<h2><span class="header-section-number">4.5</span> Scatter-plots</h2>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.</strong>
</p>
</div>
<div id="summary-3" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Summary</h3>
</div>
</div>
<div id="line-graphs" class="section level2">
<h2><span class="header-section-number">4.6</span> Line-graphs</h2>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
<p>
<strong>4.</strong>
</p>
</div>
<div id="summary-4" class="section level3">
<h3><span class="header-section-number">4.6.1</span> Summary</h3>
</div>
</div>
<div id="brief-review-of-the-grammar-of-graphics" class="section level2">
<h2><span class="header-section-number">4.7</span> Brief Review of The Grammar of Graphics</h2>
<p>You have seen all of the major pieces behind “The Grammar of Graphics” which serves as the basis for the <code>ggplot2</code> package. Here is a summary of each part:</p>
<p><strong>May need some tweaking</strong>: <a href="http://www.ling.upenn.edu/~joseff/avml2012/" class="uri">http://www.ling.upenn.edu/~joseff/avml2012/</a></p>
<div id="review-questions" class="section level3">
<h3><span class="header-section-number">4.7.1</span> Review questions</h3>
<ul>
<li>Have a variety of bad plots with data for the readers and have readers create better plots with <code>ggplot2</code></li>
</ul>
</div>
</div>
<div id="whats-to-come-1" class="section level2">
<h2><span class="header-section-number">4.8</span> What’s to come?</h2>
<p><strong>Last updated:</strong></p>
<pre><code>## [1] &quot;Friday, July 29, 2016 14:39:25 CDT&quot;</code></pre>

</div>
</div>
<h3> References</h3>
<div id="refs" class="references">
<div id="ref-wilkinson2005">
<p>Wilkinson, Leland. 2005. <em>The Grammar of Graphics (Statistics and Computing)</em>. Secaucus, NJ, USA: Springer-Verlag New York, Inc.</p>
</div>
<div id="ref-R-ggplot2">
<p>Wickham, Hadley, and Winston Chang. 2016. <em>Ggplot2: An Implementation of the Grammar of Graphics</em>. <a href="https://CRAN.R-project.org/package=ggplot2" class="uri">https://CRAN.R-project.org/package=ggplot2</a>.</p>
</div>
<div id="ref-r4ds2016">
<p>Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science</em>. O’Reilly. <a href="http://http://r4ds.had.co.nz/" class="uri">http://http://r4ds.had.co.nz/</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>To view a dataset in spreadsheet format in RStudio, you can run the <code>View()</code> function with the dataframe as its argument.<a href="viz.html#fnref1">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tidy.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="manip.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-visualizing_data.Rmd",
"text": null
},
"download": ["ismay_kim.pdf", "ismay_kim.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
